// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5OIg457eFdJA4LWLJ09tCvejeS3pfzY',
    appId: '1:812848699403:android:fd39ea60c55ec342174f0e',
    messagingSenderId: '812848699403',
    projectId: 'wave-chat-98263',
    storageBucket: 'wave-chat-98263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUvFdXpHBmqQHFCAjfoC3n6hG3ARpFGk',
    appId: '1:812848699403:ios:0ee47eb8cb6bd528174f0e',
    messagingSenderId: '812848699403',
    projectId: 'wave-chat-98263',
    storageBucket: 'wave-chat-98263.appspot.com',
    androidClientId: '812848699403-n21v1d5k0025pqhuk2prmob8acapicg1.apps.googleusercontent.com',
    iosClientId: '812848699403-ukt9ivmcm44huha4cnea1mr8t0e877s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.waveChat',
  );
}
